apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: lbservices
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      name: php-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_img # tag that we gave to the docker image when we build it
        imagePullPolicy: Never # allow to pull a local docker image
        livenessProbe:
          exec:
            command:
            - /home/script/./liveprobe.sh
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 2
        ports:
        - containerPort: 5000

