apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: lbservices
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 21
      targetPort: 21
      name: ftps
    - port: 4242
      targetPort: 4242
      name: passive-ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_img # tag that we gave to the docker image when we build it
        imagePullPolicy: Never # allow to pull a local docker image
        livenessProbe:
          exec:
            command:
            - /home/script/./liveprobe.sh
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 2
        ports:
        - containerPort: 21
        - containerPort: 4242

